username = "Player"
score = 0
coins_collected = 0
total_time=300
time_left = total_time
speed = "normal"
power_up_active = [0, 0]
control_pressed = ""
game_start_time = 0
screen_length = 120
screen_height = 30
gravity = 1
shown_until = screen_length
length_of_beam = 10
safe_region = 1
total_life=5
lives_remaining=total_life
frame_refresh_time=0.05
move_left_time=0.5
bullets_left=3 # count of deployable bullets
total_bullets=10